### ISSUE TITLE
needs threading and getting rate limited

### ISSUE THREAD

**Issue by Jimmylongnose** [Tainted06/Xbox-Code-Checker#1]
it need threading as its WAY to slow and it rates limit after about 30 codes

**Comment by Tainted06** [comment]
Yea, if you want to use it to check a lot you need to modify it to support multiple accounts. Each Microsoft account can check like 30 codes every 5 min or something like that, so you'd to add support for it to handle multiple accounts well. 

Currently it has support for adding multiple WLIDs, but that's a pain to add for a lot of accounts so it isn't a good idea. Adding code to automatically get the WLID from an account would be better, and you would probably add concurrency so that it checks multiple at the same time.

(I won't be adding that into this version)
